accounting/urls.py
from django.urls import path
from . import views
app_name='accounting'
urlpatterns = [
    path('',views.IndexView().home,name="home"),
    path('financial_year/<int:financial_year_id>/',views.IndexView().financial_year,name="financial_year"),
    path('financial_document/<int:financial_document_id>/',views.IndexView().financial_document,name="financial_document"),
    path('financial_profile/<int:financial_profile_id>/',views.IndexView().financial_profile,name="financial_profile"),
    path('financial_account/<int:financial_account_id>/',views.IndexView().financial_account,name="financial_account"),
]

app/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
app_name="app"
urlpatterns = [
    path('',views.BasicView().home,name='home'),
    path('api/',include('app.api')),
    path('my_profile/',views.ProfileView().profile,name='my_profile'),
    path('profile/<int:profile_id>/',views.ProfileView().profile,name='profile'),
    path('transactions/<int:profile_id>/',views.TransactionView().transactions,name='transactions'),    
    path('about/',views.BasicView().about,name='about'),
    path('terms/',views.BasicView().terms,name='terms'),
    path('add_tag/',views.PageView().add_tag,name='add_tag'),
    path('faq/',views.BasicView().faq,name='faq'),
    path('tag/<int:tag_id>/',views.PageView().tag,name='tag'),
    path('blogs/',views.PageView().blogs,name='blogs'),
    path('page/<int:page_id>/',views.PageView().page,name='page'),
    path('add_blog/',views.PageView().add_blog,name='add_blog'),
    path('blog/<int:blog_id>/',views.PageView().blog,name='blog'),
    path('ourworks/',views.PageView().ourworks,name='ourworks'),
    path('ourwork/<int:ourwork_id>/',views.PageView().ourwork,name='ourwork'),
    path('ourservice/<int:ourservice_id>/',views.PageView().ourservice,name='ourservice'),
    path('ourteam/<int:ourteam_id>/',views.BasicView().ourteam,name='ourteam'),
    path('resume/<int:ourteam_id>/',views.BasicView().resume,name='resume'),
    path('change_profile_image/',views.ProfileView().change_profile_image,name='change_profile_image'),
    path('edit_profile/',views.ProfileView().edit_profile,name='edit_profile'),
    path('change_profile/',views.ProfileView().change_profile,name='change_profile'),
    path('search/',views.BasicView().search,name='search'),
    path('manager/',views.ManagerView().manager,name='manager'),
    path('contact/',views.ContactView.as_view(),name='contact'),
    path('notifications/',views.BasicView().notifications,name='notifications'),
    path('notification/<int:notification_id>/',views.BasicView().notifications,name='notification'),
    path('download/<int:document_id>/',views.BasicView().download,name='download'),
    path('technology/<int:technology_id>/',views.PageView().technology,name='technology'),
    
]

authentication/urls.py
from django.urls import path
from . import views
app_name='authentication'
urlpatterns = [
    path(r'^login/(?P<next>\w{0,50})/$', views.AuthView().login,name="auth2"),
    path('login/',views.AuthView().login,name='login'),
    # path('login/',views.AuthView().login,name='login'),
    path('reset_password/',views.AuthView().reset_password,name='reset_password'),
    path('auth/',views.AuthView().auth,name='auth'),
    path('register/',views.AuthView().register,name='register'),
    path('logout/',views.AuthView().logout,name='logout'),
    path('check_available_username/',views.AuthView().check_available_username,name='check_available_username'),
    
]

leopusher/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
 
app_name='pusher'
urlpatterns = [
    path('',views.IndexView.as_view(),name='home'),
    path('beam/',views.BeamView.as_view(),name='beam'),
    path('channel/',views.BeamView.as_view(),name='channel'),
    path('channels/',views.IndexView().channels,name='channels'),
    path('channel/<int:channel_id>/',views.IndexView().channels,name='channel'),
    path('channel_event/<int:channel_event_id>',views.IndexView().channels,name='channel_event'),
    path('send_beam/',views.BeamView().send_beam,name='send_beam'),
    path('send_channel/',views.ChannelView().send_channel,name='send_channel'),
    
]

phoenix/urls.py
from django.contrib import admin
from django.urls import path,include


# from django.conf import settings
from .settings import MEDIA_URL,MEDIA_ROOT,STATIC_URL,STATIC_ROOT,DEBUG
from django.views.static import serve 
from django.conf.urls import url
from .settings import SERVER_ON_HEROKU
from app.feeder import LatestEntriesFeed,SiteMapFeeder

urlpatterns = [
    path('', include('app.urls')),
    path('phoenix_app/', include('app.urls')),
    
    path('pusher/', include('leopusher.urls')),
    path('tutorial/', include('tutorial.urls')),
    path('projectmanager/', include('projectmanager.urls')),
    path('transport/', include('transport.urls')),
    path('phoenix_api/', include('phoenix_api.urls')),
    path('accounting/', include('accounting.urls')),
    path('fa/', include('app.urls')),
    path('en/', include('engapp.urls')),
    path('automation/', include('automation.urls')),
    path('market/', include('market.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('authentication.urls')),
    path('', include('authentication.urls')),    
    path('rss/', LatestEntriesFeed(),name='feeder'),
    path('sitemap/', SiteMapFeeder(),name='sitemap'),
    url(r'^static/(?P<path>.*)$', serve,{'document_root': STATIC_ROOT}),
    url(r'^media/(?P<path>.*)$', serve,{'document_root': MEDIA_ROOT}),
      
]#+ static(STATIC_URL, document_root=STATIC_ROOT)
if SERVER_ON_HEROKU:
    from django.conf.urls.static import static
    urlpatterns=urlpatterns+static(STATIC_URL, document_root=STATIC_ROOT)

transport/urls.py
from django.urls import path
from . import views
app_name='transport'

urlpatterns = [
    path('',views.IndexView().home,name='home'),
    
]

templates/dashboard/partials/empty_search.html
<div class="col-lg-12 col-md-12 col-sm-12">
    <div class="card card-stats">
      <div class="card-header card-header-warning card-header-icon">

        <p class="card-category" style="font-size: 0.75em !important;">
          &nbsp;
        </p><a href="{{word.get_absolute_url}}">
          <h3 class="card-title text-primary"> برای جستجوی {{search_for}} نتیجه ای یافت نشد

          </h3>
        </a>
        {% if new_word_form %}


        <p class="text-muted my-0" style="font-size: 1em !important;">
          اضافه می کنید؟
        </p>
        {% endif %}
      </div>
      <div class="card-footer">
        {% if new_word_form %}


        <form action="{% url 'web:index' %}" method="POST">
          {% csrf_token %}
          <input type="hidden" name="name" value="{{search_for}}">
          <input type="hidden" name="pronounciation" value="-">
          <input type="hidden" name="definition" value="-">
<button type="submit" class="btn btn-primary" >بله</button>
        </form> {% endif %}
        <div class="stats">


          <p class="card-category">


     
            
           



          </p>
        </div>
      </div>
    </div>
  </div>

templates/dashboard/partials/footer.html
<footer class="footer">
    <div class="container-fluid">
       
        <nav class="mx-auto">
            <ul>
                <li>
                    <a href="{% url 'app:home' %}">
                        {{app.title.value}}
                    </a>
                </li>
                <li>
                    <a href="{% url 'app:about' %}">
                        درباره ما
                    </a>
                </li>
                <li>
                    <a href="{% url 'app:contact' %}">
                        ارتباط با ما
                    </a>
                </li>
            
                <li>
                    <a href="{% url 'app:terms' %}">
                        قوانین و مقررات
                    </a>
                </li>
            </ul>
        </nav>
        <div class="copyright text-center">
            &copy;
            <script>
                document.write(new Date().getFullYear())
            </script>, توسعه و طراحی
            توسط
            <a href="http://khafonline.com/" target="_blank">
                {{app.our_team_title.value}}
            </a>
        </div>
    </div>
</footer>

templates/dashboard/partials/navbar.html
{% load static %}
<!-- Navbar -->
<nav class="navbar navbar-expand-lg navbar-transparent navbar-absolute fixed-top">
    <div class="container-fluid">

        <div class="navbar-wrapper">
            <a class="navbar-brand d-lg-none mr-5" href="{% url 'app:home' %}" title="{{app.title.value}}">
                <img width="48px" src="{{app.logo.image}}" alt=""></a>

            {% if search_form %}


            <form class="navbar-form" action="{% if search_form.action %}{{search_form.action}}{% else %}{% url 'app:search' %}{% endif %}" method="POST">
                {% csrf_token %}
                <div class="input-group no-border">
                    <input required type="text" name="search_for" class="form-control" placeholder="جستجو ...">



                </div>
            </form> {% endif %}

        </div>
        <button class="navbar-toggler" type="button" data-toggle="collapse" aria-controls="navigation-index"
            aria-expanded="false" aria-label="Toggle navigation">
            <span class="sr-only">Toggle navigation</span>
            <span class="navbar-toggler-icon icon-bar"></span>
            <span class="navbar-toggler-icon icon-bar"></span>
            <span class="navbar-toggler-icon icon-bar"></span>

        </button>
        <div class="collapse navbar-collapse justify-content-end">
            <!-- <form class="navbar-form">
                <div class="input-group no-border">
                    <input type="text" value="" class="form-control" placeholder="جستجو...">
                    <button type="submit" class="btn btn-white btn-round btn-just-icon">
                        <i class="material-icons">search</i>
                        <div class="ripple-container"></div>
                    </button>
                </div>
            </form> -->
            <ul class="navbar-nav">
                {% if perms.app.change_parameter %}

                <li class="nav-item">
                    <a class="nav-link" href="{{ADMIN_URL}}">
                        <i class="material-icons">settings</i>
                        <p class="d-lg-none d-md-block">
                            ادمین
                        </p>
                    </a>
                </li>
                {% endif %}
                {% if profile %}

                <li class="nav-item dropdown" id="app-notifications" v-cloak>
                    <a class="nav-link" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown"
                        aria-haspopup="true" aria-expanded="false">
                        <i class="material-icons">notifications</i>
                        <span class="notification" v-show="notifications.length>0">
                            {% verbatim %}

                            {{notifications_count}}
                            {% endverbatim %}</span>
                        <p class="d-lg-none d-md-block">
                            اعلان‌ها
                        </p>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">

                        <div v-for="notification in notifications">







                            {% verbatim %}



                                <a :href="notification.get_absolute_url" :class="'mt-1 mb-1 nav-link text-light btn btn-'+notification.color"><i class="material-icons"
                                        data-notify="icon">{{notification.icon}}</i>
                                   {{notification.title}}
                                 
                                </a>



                   
                            {% endverbatim %}



                        </div>

                        <a href="{% url 'app:notifications'  %}" class="mt-1 mb-1 nav-link "><i class="material-icons"
                            data-notify="icon">alarm</i>
                       نمایش همه پیام ها
                     
                    </a>



                    </div>
                </li>

                {% endif %}





                {% if profile %}



                <li class="nav-item dropdown">
                    <a class="nav-link" href="javascript:;" id="navbarDropdownProfile344" data-toggle="dropdown"
                        aria-haspopup="true" aria-expanded="false">
                        <img src="{{profile.image}}" width="24px" class="rounded-circle" alt="">

                        <span class="d-lg-none">
                            &nbsp;&nbsp;&nbsp;

                            {{profile.name}}
                        </span>
                        <div class="ripple-container"></div>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownProfile344">
                        <div class="mt-2 px-2">

                            <div style="margin-left: 1em;">
   <a class="my-2 d-block text-center pt-2 btn btn-link" title="پروفایل" 
                            href="{{profile.get_absolute_url}}"
                            >
                            <img src="{{profile.image}}" class="rounded-circle" width="128px" alt="">
                            <br>    <br>
                            {{profile.name}}
                                <br>
                                <small>
                            {{profile.child_class}}</small>
                                </a>
                            </div>
                         
                        </div>
                       
                      
                      
                       
                        {% if profiles %}

                        <div class="mt-2 px-2">

                            <small>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                                تغییر نقش :
                            </small>



                            {% for current_profile in profiles %}
                            <form style="margin-left: 1em;" action="{% url 'app:change_profile' %}" method="POST">
                                {% csrf_token %}

                                <input type="hidden" name="actived" value="{{current_profile.id}}">
                                <button class="my-1 btn-block  btn btn-danger " type="submit">


                                    {{current_profile.child_class}}
                                    :
                                    {{current_profile.name}}
                                </button>
                            </form>

                            {% endfor %}













                        </div>
                        {% endif %}

                        <div class="dropdown-divider"></div>


                        <form action="{% url 'authentication:logout' %}" action="GET">
                            <!-- <button class=" btn btn-sm btn-danger">
            <i class="material-icons">power_setting</i>
          
        </button> -->

                            <button class="btn btn-link text-danger " type="submit">


                                خروج کاربر</button>

                        </form>


                    </div>
                </li>
                {%else%}
                <li class="nav-item dropdown">
                    <a class="nav-link" href="{% url 'authentication:login' %}">

                        <i class="material-icons">vpn_key</i>
                        <p class="d-lg-none d-md-block">
                            ورود
                        </p>
                    </a>

                </li>
                {% endif %}

            </ul>
        </div>
    </div>
</nav>
<!-- End Navbar -->

templates/dashboard/partials/profile_modal_cart old.html
{% if current_profile %}
<!-- Modal -->
<div class="modal fade" id="ProfilaModal" tabindex="-1" role="dialog" aria-labelledby="ProfilaModalLabel"
    aria-hidden="true">
    <div class="modal-dialog">
        <div class="">

            <div class="modal-content card card-stats">
                <div class="card-header card-header-primary card-header-icon">
                    <div style="border-radius: 600px ;padding:10px !important;" class="card-icon">

                        <img style="border-radius: 130px ;" src="{{current_profile.get_image}}" width="130px"
                            height="130px" alt="">
                    </div>
                  <p class="card-category">&nbsp;</p>
                    <a href="{% url 'app:profile' %}"> <h3 class="card-title mx-2">
                        <span  class="mx-2"> {{current_profile.name}}</span></h3></a>
                </div>
                <div class="card-body">
                    <a href="{% url 'app:home' %}">دشبورد</a>
                   
                    <small class="px-3 text-secondary">تغییر نقش&nbsp;:&nbsp;</small>
                

                    {% if current_customer %}
                    <form action="{% url 'app:change_profile' %}" method="POST">
                        {% csrf_token %}

                        <input type="hidden" name="actived" value="{{current_customer.id}}">
                        <button class=" btn btn-success " type="submit">

                            <i class="material-icons">settings</i>
                            مشتری
                            :
                            {{current_customer.name}}
                        

                        </button>
                    </form>
                    {% endif %}




                    {% if current_supplier %}
                    <form action="{% url 'app:change_profile' %}" method="POST">
                        {% csrf_token %}

                        <input type="hidden" name="actived" value="{{current_supplier.id}}">
                        <button class=" btn btn-danger " type="submit">

                            <i class="material-icons">store</i>
                            فروشنده
                            :
                            {{current_supplier.name}}
                        </button>
                    </form>
                    {% endif %}




                    {% if current_shipper %}
                    <form action="{% url 'app:change_profile' %}" method="POST">
                        {% csrf_token %}

                        <input type="hidden" name="actived" value="{{current_shipper.id}}">
                        <button class=" btn btn-warning " type="submit">

                            <i class="material-icons">local_shipping</i>
                            پیک
                            :
                            {{current_shipper.name}}
                        </button>
                    </form>
                    {% endif %}



                    {% if current_employee %}
                    <form action="{% url 'app:change_profile' %}" method="POST">
                        {% csrf_token %}

                        <input type="hidden" name="actived" value="{{current_employee.id}}">
                        <button class=" btn btn-info" type="submit">

                            <i class="material-icons">group_work</i>
                            کارمند
                            :
                            {{current_employee.name}}
                        </button>
                    </form>
                    {% endif %}




                    <form action="{% url 'app:logout' %}" action="GET">
                        <!-- <button class=" btn btn-sm btn-danger">
                            <i class="material-icons">power_setting</i>
                          
                        </button> -->

                        <button class="btn btn-link text-danger " type="submit">

                            <i class="material-icons">power_settings_new</i>
                            <span>خروج</span></button>

                    </form>
                </div>

                <div class="card-footer">
                    
                    <div class="stats">
                        <p>
                          
                            <span>آخرین ورود&nbsp;:&nbsp;{{current_profile.user.last_login | to_persian_date}}</span>
                        </p>
                    </div>
                </div>
            </div>


        </div>
    </div>
</div>
{% endif %}

templates/dashboard/partials/sidebar.html
{% load static %}

<li class="nav-item " id="dashboard-link">
    <a class="nav-link" href="{% url 'app:home' %}">
        <i class="material-icons">home</i>
        <p>خانه</p>
    </a>
</li>

{% if profile %}
  
<li class="nav-item " id="dashboard-profile-link">
    <a class="nav-link" href="{% url 'app:profile' profile.id %}">
       
        <i class="fa fa-user"></i>
        <p>{{profile.name}}</p>
    </a>
</li>
<li class="nav-item " id="project-manager-link">
    <a class="nav-link" href="{% url 'projectmanager:home'%}">
       
        <i class="material-icons">construction</i>
        <p>مدیریت پروژه</p>
    </a>
</li>
<li class="nav-item " id="chart-link">
    <a class="nav-link" href="{% url 'projectmanager:chart'%}">
       
        <i class="material-icons">apartment</i>
        <p>چارت سازمانی</p>
    </a>
</li>
<li class="nav-item " id="chart-link">
    <a class="nav-link" href="{% url 'app:manager'%}">
        <i class="material-icons">chat</i>
         <p>پیام رسان</p>
    </a>
</li>

{% endif %}
{% if PUSHER_IS_ENABLE %}
  
<li class="nav-item " id="pusher-link">
    <a class="nav-link" href="{% url 'pusher:home'%}">
        <i class="fa fa-user"></i>
         <p>پوشر</p>
    </a>
</li>

{% endif %}
<li class="nav-item " id="tutorial-link">
    <a class="nav-link" href="{% url 'tutorial:home' %}">
        <i class="material-icons">flash_auto</i>
        <p>آموزش</p>
    </a>
</li>


<li class="nav-item " id="accounting-link">
    <a class="nav-link" href="{% url 'accounting:home' %}">
        <i class="fa fa-money"></i>
        <p>حسابداری</p>
    </a>
</li>





<li class="nav-item " id="transport-link">
    <a class="nav-link" href="{% url 'transport:home' %}">
        <i class="fa fa-bus"></i>
        <p>مدیریت ماشین آلات
        </p>
    </a>
</li>












<li class="nav-item " id="temp-link">
    <a class="nav-link" href="">
        
        <p>&nbsp</p>
    </a>
</li>