app/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
app_name="app"
urlpatterns = [
    path('',views.BasicView().home,name='home'),
    path('api/',include('app.api')),
    path('my_profile/',views.ProfileView().profile,name='my_profile'),
    path('profile/<int:profile_id>/',views.ProfileView().profile,name='profile'),
    path('transactions/<int:profile_id>/',views.TransactionView().transactions,name='transactions'),    
    path('about/',views.BasicView().about,name='about'),
    path('terms/',views.BasicView().terms,name='terms'),
    path('add_tag/',views.PageView().add_tag,name='add_tag'),
    path('faq/',views.BasicView().faq,name='faq'),
    path('tag/<int:tag_id>/',views.PageView().tag,name='tag'),
    path('blogs/',views.PageView().blogs,name='blogs'),
    path('page/<int:page_id>/',views.PageView().page,name='page'),
    path('add_blog/',views.PageView().add_blog,name='add_blog'),
    path('blog/<int:blog_id>/',views.PageView().blog,name='blog'),
    path('ourworks/',views.PageView().ourworks,name='ourworks'),
    path('ourwork/<int:ourwork_id>/',views.PageView().ourwork,name='ourwork'),
    path('ourservice/<int:ourservice_id>/',views.PageView().ourservice,name='ourservice'),
    path('ourteam/<int:ourteam_id>/',views.BasicView().ourteam,name='ourteam'),
    path('resume/<int:ourteam_id>/',views.BasicView().resume,name='resume'),
    path('change_profile_image/',views.ProfileView().change_profile_image,name='change_profile_image'),
    path('edit_profile/',views.ProfileView().edit_profile,name='edit_profile'),
    path('change_profile/',views.ProfileView().change_profile,name='change_profile'),
    path('search/',views.BasicView().search,name='search'),
    path('manager/',views.ManagerView().manager,name='manager'),
    path('contact/',views.ContactView.as_view(),name='contact'),
    path('notifications/',views.BasicView().notifications,name='notifications'),
    path('notification/<int:notification_id>/',views.BasicView().notifications,name='notification'),
    path('download/<int:document_id>/',views.BasicView().download,name='download'),
    path('technology/<int:technology_id>/',views.PageView().technology,name='technology'),
    
]

phoenix/urls.py
from django.contrib import admin
from django.urls import path,include


# from django.conf import settings
from .settings import MEDIA_URL,MEDIA_ROOT,STATIC_URL,STATIC_ROOT,DEBUG
from django.views.static import serve 
from django.conf.urls import url
from .settings import SERVER_ON_HEROKU
from app.feeder import LatestEntriesFeed,SiteMapFeeder

urlpatterns = [
    path('', include('app.urls')),
    path('phoenix_app/', include('app.urls')),
    
    path('pusher/', include('leopusher.urls')),
    path('tutorial/', include('tutorial.urls')),
    path('projectmanager/', include('projectmanager.urls')),
    path('transport/', include('transport.urls')),
    path('phoenix_api/', include('phoenix_api.urls')),
    path('accounting/', include('accounting.urls')),
    path('fa/', include('app.urls')),
    path('en/', include('engapp.urls')),
    path('automation/', include('automation.urls')),
    path('market/', include('market.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('authentication.urls')),
    path('', include('authentication.urls')),    
    path('rss/', LatestEntriesFeed(),name='feeder'),
    path('sitemap/', SiteMapFeeder(),name='sitemap'),
    url(r'^static/(?P<path>.*)$', serve,{'document_root': STATIC_ROOT}),
    url(r'^media/(?P<path>.*)$', serve,{'document_root': MEDIA_ROOT}),
      
]#+ static(STATIC_URL, document_root=STATIC_ROOT)
if SERVER_ON_HEROKU:
    from django.conf.urls.static import static
    urlpatterns=urlpatterns+static(STATIC_URL, document_root=STATIC_ROOT)

projectmanager/urls.py
from django.urls import path
from . import views
from django.contrib.auth.decorators import login_required, permission_required

app_name='projectmanager'
urlpatterns = [
    path('',login_required(views.BasicView().home),name='home'),
    path('resume/',views.BasicView().resume,name='resume'),
    path('add_assignment/',views.ManagerPageView().add_assignment,name='add_assignment'),
    path('add_archivedocument/',views.ManagerPageView().add_archivedocument,name='add_archivedocument'),
    path('add_archivecategory/',views.ManagerPageView().add_archivecategory,name='add_archivecategory'),
    path('add_location/',views.ManagerPageView().add_location,name='add_location'),
    path('add_issue/',views.ManagerPageView().add_issue,name='add_issue'),
    path('add_project/',views.ManagerPageView().add_project,name='add_project'),
    path('add_workunit/',views.ManagerPageView().add_workunit,name='add_workunit'),
    # path('add_link/',login_required(views.ManagerPageView().add_link),name='add_link'),
    path('tag/<int:tag_id>/',views.ManagerPageView().tag,name='tag'),
    
    path('add_link/', permission_required(app_name+'.add_link')(views.ManagerPageView().add_link),name='add_link'),
    path('add_material/',views.ManagerPageView().add_material,name='add_material'),
    path('add_material_category/',views.ManagerPageView().add_material_category,name='add_material_category'),
    
    path('add_document/',views.ManagerPageView().add_document,name='add_document'),
    path('add_tag/',views.ManagerPageView().add_tag,name='add_tag'),
    path('search/',views.BasicView().search,name='search'),

    path('projectcategory/<int:category_id>/',views.BasicView().home,name='project_category'),
    path('issue/<int:issue_id>/',views.ManagerPageView().issue,name='issue'),
    path('assignment/<int:assignment_id>/',views.ManagerPageView().assignment,name='assignment'),
    path('page/<int:page_id>/',views.ManagerPageView().page,name='page'),
    path('assignment/<int:assignment_id>/',views.ManagerPageView().assignment,name='assignment'),
    path('project/<int:project_id>/',views.ManagerPageView().project,name='project'),
    path('project_avo/<int:project_id>/',views.ManagerPageView().project_avo,name='project_avo'),
    path('workunit/<int:work_unit_id>/',views.ManagerPageView().work_unit,name='work_unit'),
    path('materialcategory/<int:category_id>/',views.ManagerPageView().materialcategory,name='materialcategory'),
    path('materialrequest/<int:material_request_id>/',views.ManagerPageView().material_request,name='material_request'),
    path('materialwarehouse/<int:materialwarehouse_id>/',views.ManagerPageView().materialwarehouse,name='materialwarehouse'),
    path('materialobject/<int:materialobject_id>/',views.ManagerPageView().materialobject,name='materialobject'),
    path('materialbrand/<int:materialbrand_id>/',views.ManagerPageView().materialbrand,name='materialbrand'),
    path('material/<int:material_id>/',views.ManagerPageView().material,name='material'),
    path('priority/',views.BasicView().priority,name='priority'),
    path('add_material_request/',views.ManagerPageView().add_material_request,name='add_material_request'),
    path('sign_material_request/',views.ManagerPageView().sign,name='sign_material_request'),
    path('chart/',views.BasicView().chart,name='chart'), 
    path('archivecategory/<int:archivecategory_id>/',views.ManagerPageView().archivecategory,name='archivecategory'),
    path('archivedocument/<int:archivedocument_id>/',views.ManagerPageView().archivedocument,name='archivedocument'),
 ]

market/models.py
from .apps import APP_NAME
from django.db import models
from django.db.models import Avg, Max, Min
from django.conf import settings
from django.shortcuts import reverse
from django.core.files.uploadedfile import InMemoryUploadedFile
from django.utils import timezone
from django.utils.translation import gettext as _
from io import BytesIO
from .enums import ProfileEnum,OrderStatusEnum
from .constants import *
from app.enums import EmployeeEnum,DegreeLevelEnum,TransactionDirectionEnum, IconsEnum, RegionEnum,AddressTitleEnum
from app.persian import PersianCalendar
from app.repo import ParameterRepo
from app.models import Profile
from app.settings import ADMIN_URL,MEDIA_URL,STATIC_URL
from PIL import Image
from tinymce import models as tinymce_models
import re
import sys
IMAGE_FOLDER=APP_NAME+'/images/'

class ProductUnit(models.Model):
    name=models.CharField(_("واحد فروش"), max_length=50)  
    priority=models.IntegerField(_("ترتیب"),default=1000)

    class Meta:
        verbose_name = _("ProductUnit")
        verbose_name_plural = _("واحد فروش کالا ها")

    def __str__(self):
        return self.name

class Shop(models.Model):
    
    supplier=models.ForeignKey("Supplier", verbose_name=_("فروشگاه"), on_delete=models.CASCADE)
    unit_name=models.CharField(_("واحد فروش"), max_length=50,default='عدد')
    product=models.ForeignKey("Product", verbose_name=_("محصول انتخابی"), on_delete=models.CASCADE)
    price=models.IntegerField(_("قیمت"),default=0)
    available=models.IntegerField(_("تعداد موجودی"),default=DEFAULT_AVAILABLE_PRODUCT_FOR_SHOP)
    time_added=models.DateTimeField(_("تاریخ ثبت پیشنهاد"), auto_now=False, auto_now_add=True)
    description=models.CharField(_("توضیحات"), max_length=500,null=True,blank=True)
    class Meta:
        verbose_name = _("Shop")
        verbose_name_plural = _("کالاهای آماده فروش")

    def __str__(self):
        return self.supplier.title+' (( '+self.product.name+' )) [[ '+(self.unit_name)+' ]]=>  '+str(self.price)
    def product_image(self):
        return str(self.product.image)
    def product_name(self):
        return self.product.name
    def get_absolute_url(self):
        return reverse("market:supplier", kwargs={"supplier_id": self.supplier.pk})
 
class Category(models.Model):
    icon=models.CharField(_("icon"),choices=IconsEnum.choices,default=IconsEnum.important_devices, max_length=50)
    parent=models.ForeignKey("Category", verbose_name=_("دسته بندی بالاتر"),on_delete=models.PROTECT,blank=True,null=True)
    prefix=models.CharField(_("پیش تعریف"), max_length=200,default='',null=True,blank=True)
    name=models.CharField(_("نام دسته"), max_length=50)
    description=models.CharField(_("توضیحات"), max_length=500,default='',null=True,blank=True)
    image_origin=models.ImageField(_("تصویر"), upload_to=IMAGE_FOLDER+'Category/', height_field=None, width_field=None, max_length=None,blank=True,null=True)
    rate=models.IntegerField(_("امتیاز"),default=0)
    priority=models.IntegerField(_("ترتیب"),default=1000)
    def image(self):
        return self.image_origin
    def get_nav_li(self):
        template=f"""
        <li>
            <a href="{self.get_absolute_url()}" class="leo-farsi">{self.name}<i class="fas fa-chevron-down"></i></a>
        """
        if self.childs():
            template+="""<ul style="left: -100px;position: absolute;">"""
            for category in self.childs():
                template+=category.get_nav_li()
            template+="</ul>"
        template+="</li>"
        return template
    def get_nav_li2(self):
        template=f"""
        <li>
            <a href="{self.get_absolute_url()}"  class="leo-farsi">{self.name}<i class="fas fa-chevron-down"></i></a>
        """
        if self.childs():
            template+="""<ul>"""
            for category in self.childs():
                template+=category.get_nav_li2()
            template+="</ul>"
        template+="</li>"
        return template
    # def top_products(self):
    #     category_id=self.pk
    #     # products=Product.objects.filter(category_id=category_id)
    #     # for child in Category.objects.filter(parent_id=category_id):
    #     #     products=products | child.top_products(child.id)
    #     # return products[:5]
    #     category_repo=CategoryRepo(user=self.user)
        
    #     products=list(self.list(category_id=category_id).values('id','name'))
    #     for child in category_repo.list(parent_id=category_id):
    #         products+=(self.top_products(child.id))
    #     return products
    def childs(self):
        return Category.objects.filter(parent=self)
    def save(self):
        if not self.image_origin:
            super(Category,self).save()             
        elif str(self.image_origin)==str(Category.objects.get(pk=self.id).image_origin):
            super(Category,self).save()
        elif self.image_origin and FORCE_RESIZE_IMAGE:
            # try:
            #     unused_image=Category.objects.get(pk=self.id).image
            #     if unused_image is not None:
            #         input(unused_image)
            #         #unused_image= Image.open(unused_image)
            #         input(unused_image.name)
            #         os.remove(unused_image.name)
            # except:
            #     pass

            #Opening the uploaded image
            image = Image.open(self.image_origin)
       
            output = BytesIO()
           

            #Resize/modify the image
            image = image.resize( (CATEGORY_IMAGE_WIDTH,CATEGORY_IMAGE_HEIGHT),Image.ANTIALIAS )
          
            #after modifications, save it to the output
            image.save(output, format='JPEG', quality=95)
           
            output.seek(0)
           

            #change the imagefield value to be the newley modifed image value
            self.image_origin = InMemoryUploadedFile(output,'ImageField', "%s.jpg" %self.image.name.split('.')[0], IMAGE_FOLDER+'Category/image/jpeg', sys.getsizeof(output), None)
            
        super(Category,self).save()
    class Meta:
        verbose_name = _("Category")
        verbose_name_plural = _("دسته بندی ها")

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("market:list", kwargs={"parent_id": self.pk})
  
    def get_edit_url(self):
        return ADMIN_URL+APP_NAME+'/category/'+str(self.pk)+'/change/'
    
    def get_breadcrumb_li(self):
        if self is None:
            home='<li class="breadcrumb-item"><a href="'+reverse('market:list',kwargs={'parent_id':0})+'">خانه</a></li>'        
            return home
        this_category_li='<li class="breadcrumb-item"><a href="'+reverse('market:list',kwargs={'parent_id':self.pk})+'">'+self.name+'</a></li>'  
        return Category.get_breadcrumb_li(self.parent)+this_category_li

    # def get_breadcrumb_li(self):
    #     if self.parent is None:
    #         home='<li class="breadcrumb-item"><a href="'+reverse('market:list',kwargs={'parent_id':0})+'">خانه</a></li>'        
    #         return home+'<li class="breadcrumb-item"><a href="'+reverse('market:list',kwargs={'parent_id':self.id})+'">'+self.name+'</a></li>'  
    #     else:
    #         return self.parent.get_breadcrumb_li()+self.get_breadcrumb_li()
    def get_breadcrumb(self):
        startnav='<nav aria-label="breadcrumb"><ol class="breadcrumb" style="background:none !important;">'
        inside=Category.get_breadcrumb_li(self)         
        endnav='</ol></nav>'
        return startnav+inside+endnav
 
class Brand(models.Model):
    prefix=models.CharField(_("پیش تعریف"), max_length=200,default='',null=True,blank=True)
    name=models.CharField(_("نام برند"), max_length=50)
    description=models.CharField(_("توضیحات"), max_length=500,default='',null=True,blank=True)
    image_origin=models.ImageField(_("تصویر"), upload_to=IMAGE_FOLDER+'Brand/', height_field=None, width_field=None, max_length=None,blank=True,null=True)
    rate=models.IntegerField(_("امتیاز"),default=0)
    priority=models.IntegerField(_("ترتیب"),default=1000)
    url=models.CharField(_("آدرس اینترتی"),null=True,blank=True,max_length=100)
    def image(self):
        return MEDIA_URL+str(self.image_origin)
    
    # def top_products(self):
    #     category_id=self.pk
    #     # products=Product.objects.filter(category_id=category_id)
    #     # for child in Category.objects.filter(parent_id=category_id):
    #     #     products=products | child.top_products(child.id)
    #     # return products[:5]
    #     category_repo=CategoryRepo(user=self.user)
        
    #     products=list(self.list(category_id=category_id).values('id','name'))
    #     for child in category_repo.list(parent_id=category_id):
    #         products+=(self.top_products(child.id))
    #     return products

    class Meta:
        verbose_name = _("Brand")
        verbose_name_plural = _("برند ها")

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("market:brand", kwargs={"brand_id": self.pk})
        # return self.url
    def get_edit_url(self):
        return ADMIN_URL+APP_NAME+'/brand/'+str(self.pk)+'/change/'
    
    def get_breadcrumb_li(self):
        if self is None:
            home='<li class="breadcrumb-item"><a href="'+reverse('market:list',kwargs={'parent_id':0})+'">خانه</a></li>'        
            return home
        this_category_li='<li class="breadcrumb-item"><a href="'+reverse('market:list',kwargs={'parent_id':self.pk})+'">'+self.name+'</a></li>'  
        return Category.get_breadcrumb_li(self.parent)+this_category_li

    # def get_breadcrumb_li(self):
    #     if self.parent is None:
    #         home='<li class="breadcrumb-item"><a href="'+reverse('market:list',kwargs={'parent_id':0})+'">خانه</a></li>'        
    #         return home+'<li class="breadcrumb-item"><a href="'+reverse('market:list',kwargs={'parent_id':self.id})+'">'+self.name+'</a></li>'  
    #     else:

templates/projectmanager/archive-category.html
{% extends "projectmanager/page.html" %}

templates/projectmanager/archive-document.html
{% extends "projectmanager/page.html" %}

templates/projectmanager/index.html
{% extends "dashboard/layout.html" %}
{% load static %}
{% load to_price %}
{% block contents %}





<div class="row">



  <div class="col-lg-4 col-md-6 col-sm-12">
    <!-- project categories -->
    <div class="card card-stats">
      <div class="card-header card-header-info card-header-icon">
        <div class="card-icon">
          <i class="material-icons">settings</i>
        </div>
        <p class="card-category">لیست</p>
        <h3 class="card-title">دسته بندی پروژه ها

        </h3>
      </div>
      <div class="card-body">

        {% for project_category in project_categories %}


        <h4 class="mt-4 text-secondary">

          <i class="material-icons">dashboard</i>
          {{project_category.title}}

        </h4>
        <div class="my-3">
          {% for project in project_category.project_set.all %}
          <div class="mb-3">
            <h6>
              <a class="d-inline mx-5 text-primary" href="{{project.get_absolute_url}}">
                {{project.get_colored_icon|safe}}
                {{project.title}}</a>
              <span class="badge badge-{{project.get_status_color}}">{{project.status}}</span>

            </h6>
          </div>
          {% endfor %}
        </div>
        </p>
        <hr>
        {% endfor %}
      </div>
      <div class="card-footer">
        <div class="stats">
          {% if perms.projectmanager.add_project %}
          <i class="material-icons text-danger">link</i>

          <a href="{{ADMIN_URL}}{{APP_NAME}}/project/add/">

            اضافه کردن پروژه</a>
          {% endif %}


          {% if perms.projectmanager.add_projectcategory %}
          <i class="material-icons text-danger ml-4">link</i>

          <a href="{{ADMIN_URL}}{{APP_NAME}}/projectcategory/add/">

            اضافه کردن دسته جدید</a>
          {% endif %}
        </div>
      </div>
    </div>

  </div>
  <!-- material categories -->
  <div class="col-lg-4 col-md-6 col-sm-12">
    <div class="card card-stats">
      <div class="card-header card-header-info card-header-icon">
        <div class="card-icon">
          <i class="material-icons">settings</i>
        </div>
        <p class="card-category">لیست</p>
        <h3 class="card-title">دسته بندی های متریال

        </h3>
      </div>
      <div class="card-body">

        {% for material_category in material_categories %}

        <a href="{{material_category.get_absolute_url}}">
          <h4 class="mt-4 text-primary">

            <i class="material-icons">dashboard</i>
            {{material_category.title}}

          </h4>
        </a>

        <hr>
        {% endfor %}
      </div>
      <div class="card-footer">
        <div class="stats">
          {% if perms.projectmanager.add_materialcategory %}
          <i class="material-icons text-danger">link</i>

          <a href="{{ADMIN_URL}}{{APP_NAME}}/materialcategory/add/">

            اضافه کردن دسته بندی متریال</a>
          {% endif %}



        </div>
      </div>
    </div>



  </div>
  
  <!-- material warehouses -->
  <div class="col-lg-4 col-md-6 col-sm-12">
    <div class="card card-stats">
      <div class="card-header card-header-info card-header-icon">
        <div class="card-icon">
          <i class="material-icons">settings</i>
        </div>
        <p class="card-category">لیست</p>
        <h3 class="card-title">انبار های متریال

        </h3>
      </div>
      <div class="card-body">

        {% for material_warehouse in material_warehouses %}

             {{material_warehouse.get_link|safe}}

         
       

        {% endfor %}
      </div>
      <div class="card-footer">
        <div class="stats">
          {% if perms.projectmanager.add_materialcategory %}
          <i class="material-icons text-danger">link</i>

          <a href="{{ADMIN_URL}}{{APP_NAME}}/materialwarehouse/add/">

            اضافه کردن انبار متریال</a>
          {% endif %}



        </div>
      </div>
    </div>



  </div>


 

  <!-- archive categories -->
  <div class="col-lg-4 col-md-6 col-sm-12">
    <div class="card card-stats">
      <div class="card-header card-header-info card-header-icon">
        <div class="card-icon">
          <i class="material-icons">settings</i>
        </div>
        <p class="card-category">لیست</p>
        <h3 class="card-title">دسته بندی اسناد آرشیوی

        </h3>
      </div>
      <div class="card-body">

        {% for archivecategory in archivecategories %}

             {{archivecategory.get_link|safe}}

         
       

        {% endfor %}
      </div>
      <div class="card-footer">
        <div class="stats">
          {% if perms.projectmanager.add_archivecategory %}
          <i class="material-icons text-danger">link</i>

          <a href="{{ADMIN_URL}}{{APP_NAME}}/archivecategory/add/">

            اضافه کردن دسته بندی اسناد </a>
          {% endif %}



        </div>
      </div>
    </div>



  </div>



</div>


{% endblock %}
{% block scripts %}
<script>



  $(document).ready(function () {
    // Javascript method's body can be found in assets/js/demos.js
    // initDashboardPageCharts();

  });
</script>
<script>
  $("#project-manager-link").addClass("active");


  $(".go_up_btn:first").addClass('d-none')

  $(".go_down_btn:last").addClass('d-none')


</script>
{% endblock %}
{% block styles %}

{% endblock %}

templates/projectmanager/issue.html
{% extends "projectmanager/page.html" %} {% load static %} 
{% load to_price %} {% block content %}



<div class="col-lg-6">
    سیسشیسش
</div>

{% endblock %}

templates/projectmanager/material-category.html
{% extends "projectmanager/page.html" %} 
{% load static %} 
{% load to_price %} 

                  
{% block content %}

                {% endblock %}


{% block first %}



    <div class="col-12">
        <div class="card card-stats">
            <div class="card-header card-header-{{category.color}} card-header-icon">
                <div class="card-icon">
                    {{category.get_icon|safe}}
                </div>

                {% if category.parent %}
                <p class="card-category">
                    {{category.parent.get_breadcrumb_url | safe}}
                </p>
                {% endif %}

                <p class="card-category">{{category.title}}</p>


                <h3 class="card-title">زیر مجموعه
                </h3>
            </div>
            <div class="card-body">

           

                {% for material_category in category.childs %}
                <a href="{{material_category.get_absolute_url}}">
                    <h5>
                        <i class="material-icons">category
                        </i> {{material_category.title}}
                    </h5>
                </a>
                {% endfor %}
               
              {% if add_material_category_form %}
                <div>
                    <form action="{% url 'projectmanager:add_material_category' %}" method="POST">
                        {% csrf_token %}
                        <input type="hidden" name="parent_id" value="{{category.id}}">
                        <input placeholder="نام دسته جدید" type="text" name="title" class="form-control" id="">
                        <button class="btn btn-success" type="submit">افزودن</button>
                    </form>
                </div>
              {% endif %}
            </div>
            <div class="card-footer">
                <div class="stats">
                    {% if perms.projectmanager.change_category and category.get_edit_url%}
                    <i class="material-icons text-danger">settings</i>

                    <a href="{{category.get_edit_url}}">

                        ویرایش </a> {% endif %} {% if perms.projectmanager.add_material %}
                    <i class="material-icons text-danger">settings</i>

                    <a href="{{ADMIN_URL}}{{APP_NAME}}/material/add/">

                        افزودن متریال  </a> {% endif %}
                </div>
            </div>
        </div>
    </div>
   
    <div class="col-12">
        <div class="card card-stats">
            <div class="card-header card-header-info card-header-icon">
                <div class="card-icon">
                    <i class="material-icons">category</i>
                </div>



                <p class="card-category">{{category.title}}</p>


                <h3 class="card-title">متریال ها


                </h3>
            </div>
            <div class="card-body">

{% if category.materials %}
  

                {% for material in category.materials %}
                <a href="{{material.get_absolute_url}}">
                    <h5>
                        <i class="material-icons">category
                        </i> {{material.title}}
                    </h5>
                </a>
                {% endfor %}

                {% endif %}

                {% if add_material_form %}
                <div>
                    <form action="{% url 'projectmanager:add_material' %}" method="POST">
                        {% csrf_token %}
                        <input type="hidden" name="category_id" value="{{category.id}}">
                        <input placeholder="نام متریال جدید" type="text" name="title" class="form-control" id="">
                        <button class="btn btn-success" type="submit">افزودن</button>
                    </form>
                </div>
              {% endif %}

            </div>
            <div class="card-footer">
                <div class="stats">
                    {% if perms.projectmanager.change_category and category.get_edit_url%}
                    <i class="material-icons text-danger">settings</i>

                    <a href="{{category.get_edit_url}}">

                        ویرایش </a> {% endif %}
                </div>
            </div>
        </div>
    </div>
    

    



{% endblock %}

templates/projectmanager/report.html
<p>
    <a class="btn btn-primary" data-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample">
      Link with href
    </a>
    <button class="btn btn-primary" type="button" data-toggle="collapse" data-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
      Button with data-target
    </button>
  </p>
  <div class="collapse" id="collapseExample">
    <div class="card card-body">
      Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. Nihil anim keffiyeh helvetica, craft beer labore wes anderson cred nesciunt sapiente ea proident.
    </div>
  </div>

templates/projectmanager/resume.html
<!DOCTYPE html>
<html lang="en">
{% load static %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Resume</title>
    <link rel="stylesheet" href="{% static 'vendor/css/bootstrap.min.css' %} ">
    <link rel="stylesheet" href="{% static 'vendor/css/font-awesome.min.css' %} ">
    <link rel="stylesheet" href="{% static 'dashboard/leo/leo.css' %}" />
<style>
    body{
        background-color: #002b34;
        color: white;
    }
    .bar{
        background-color: #ffc300;
    }
    hr{
        background-color: #3a4f4c;
    }
</style>
</head>

<body>
    {% for r in count %}
         <div class="container">
        <div class="row">
            <div class="col-lg-3">
                <div class="row">
                    <div class="col-4">asdasd</div>
                    <div class="col-3 bar" style="height: 100%;">sdsd</div>
                    <div class="col-5">sadsa sd</div>
                </div>
               
            </div>
            <div class="col-lg-9">sdgdsgfdg <hr></div>
        </div>
       
    </div>
    {% endfor %}
 

    <script src="{% static 'vendor/js/jquery.slim.min.js' %}"></script>
    <script src="{% static 'vendor/js/popper.min.js' %}"></script>
    <script src="{% static 'vendor/js/bootstrap.min.js' %}"></script>
</body>

</html>

templates/projectmanager/work-unit.html
{% extends "projectmanager/page.html" %} {% load static %}
 {% load to_price %} {% block content %}






{% endblock %}