app/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
app_name="app"
urlpatterns = [
    path('',views.BasicView().home,name='home'),
    path('api/',include('app.api')),
    path('my_profile/',views.ProfileView().profile,name='my_profile'),
    path('profile/<int:profile_id>/',views.ProfileView().profile,name='profile'),
    path('transactions/<int:profile_id>/',views.TransactionView().transactions,name='transactions'),    
    path('about/',views.BasicView().about,name='about'),
    path('terms/',views.BasicView().terms,name='terms'),
    path('add_tag/',views.PageView().add_tag,name='add_tag'),
    path('faq/',views.BasicView().faq,name='faq'),
    path('tag/<int:tag_id>/',views.PageView().tag,name='tag'),
    path('blogs/',views.PageView().blogs,name='blogs'),
    path('page/<int:page_id>/',views.PageView().page,name='page'),
    path('add_blog/',views.PageView().add_blog,name='add_blog'),
    path('blog/<int:blog_id>/',views.PageView().blog,name='blog'),
    path('ourworks/',views.PageView().ourworks,name='ourworks'),
    path('ourwork/<int:ourwork_id>/',views.PageView().ourwork,name='ourwork'),
    path('ourservice/<int:ourservice_id>/',views.PageView().ourservice,name='ourservice'),
    path('ourteam/<int:ourteam_id>/',views.BasicView().ourteam,name='ourteam'),
    path('resume/<int:ourteam_id>/',views.BasicView().resume,name='resume'),
    path('change_profile_image/',views.ProfileView().change_profile_image,name='change_profile_image'),
    path('edit_profile/',views.ProfileView().edit_profile,name='edit_profile'),
    path('change_profile/',views.ProfileView().change_profile,name='change_profile'),
    path('search/',views.BasicView().search,name='search'),
    path('manager/',views.ManagerView().manager,name='manager'),
    path('contact/',views.ContactView.as_view(),name='contact'),
    path('notifications/',views.BasicView().notifications,name='notifications'),
    path('notification/<int:notification_id>/',views.BasicView().notifications,name='notification'),
    path('download/<int:document_id>/',views.BasicView().download,name='download'),
    path('technology/<int:technology_id>/',views.PageView().technology,name='technology'),
    
]

market/urls.py
from django.urls import path,include
from .views import *
app_name='market'
urlpatterns=[  
    
    path('api/', include('market.api')),
    path('',ShopView().list,name='home'),
    path('my_list/',IndexView().my_list,name='my_list'),
    path('suppliers/',SupplierView().list,name='suppliers'),
    path('submit_cart/',CartView().submit_cart,name='submit_cart'),
    path('orders/<int:customer_id>/',OrderView().orders,name='orders'),
    path('orders_/<int:supplier_id>/',OrderView().orders,name='orders_supplier'),
    path('orders_/<int:supplier_id>/<start_date>/<end_date>/',OrderView().orders,name='orders_supplier_by_date'),
    path('orders__/<int:shipper_id>/',OrderView().orders,name='orders_shipper'),
    path('cart/<int:customer_id>/',CartView.as_view(),name='cart'),
    path('order/<int:order_id>/',OrderView().order,name='order'),
    path('do_pack_order/',OrderView().do_pack_order,name='do_pack_order'),
    path('do_deliver_order/',OrderView().do_deliver_order,name='do_deliver_order'),
    path('do_ship_order/',OrderView().do_ship_order,name='do_ship_order'),
    path('add_category/',ShopView().add_category,name='add_category'), 
    path('add_product/',ShopView().add_product,name='add_product'), 
    path('add_shop/',ShopView().add_shop,name='add_shop'), 
    path('add_product_comment/',ProductView().add_product_comment,name='add_product_comment'), 
    path('remove_shop/',ShopView().remove_shop,name='remove_shop'), 
    path('add_to_cart/',ProductView().add_to_cart,name='add_to_cart'),    
    path('remove_from_cart/',CartView().remove_from_cart,name='remove_from_cart'), 
    path('tables/',TableView().list,name='tables'),    
    path('xlsx/',ProductView().get_list_xlsx,name='xlsx'),
    path('brand/<int:brand_id>/',ShopView().brand,name='brand'),
    path('products/<int:category_id>/',ProductView().list,name='products'),
    path('product/<int:product_id>/',ProductView().product,name='product'),
    path('list/<int:parent_id>/',IndexView.as_view(),name='list'),
    path('list_vue/<int:parent_id>/',ShopView().list_vue,name='list_vue'),
    path('supplier/<int:supplier_id>/',SupplierView().supplier,name='supplier'),
    path('ware_house/<int:ware_house_id>/',WareHouseViews().ware_house,name='ware_house'),
    path('download/<int:supplier_id>/',DownloadView.as_view(),name='download'),
    path('download/order/<int:order_id>/',DownloadView().get_order,name='download_order'),
    # path('w/d/<name>/',views.WordView().word_name,name='word_name'),
    # path('new_definition/',views.WordView().new_definition,name='new_definition'),
    # path('new_word/',views.WordView().new_word,name='new_word'),
    path('add_like/',ProductView().add_like,name='add_like'),
    # path('add_dislike/',views.WordView().add_dislike,name='add_dislike'),
    path('search/',IndexView().search,name='search'),

    path('manager/',ManagerView().manager,name='manager'),
    


    
]

phoenix/urls.py
from django.contrib import admin
from django.urls import path,include


# from django.conf import settings
from .settings import MEDIA_URL,MEDIA_ROOT,STATIC_URL,STATIC_ROOT,DEBUG
from django.views.static import serve 
from django.conf.urls import url
from .settings import SERVER_ON_HEROKU
from app.feeder import LatestEntriesFeed,SiteMapFeeder

urlpatterns = [
    path('', include('app.urls')),
    path('phoenix_app/', include('app.urls')),
    
    path('pusher/', include('leopusher.urls')),
    path('tutorial/', include('tutorial.urls')),
    path('projectmanager/', include('projectmanager.urls')),
    path('transport/', include('transport.urls')),
    path('phoenix_api/', include('phoenix_api.urls')),
    path('accounting/', include('accounting.urls')),
    path('fa/', include('app.urls')),
    path('en/', include('engapp.urls')),
    path('automation/', include('automation.urls')),
    path('market/', include('market.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('authentication.urls')),
    path('', include('authentication.urls')),    
    path('rss/', LatestEntriesFeed(),name='feeder'),
    path('sitemap/', SiteMapFeeder(),name='sitemap'),
    url(r'^static/(?P<path>.*)$', serve,{'document_root': STATIC_ROOT}),
    url(r'^media/(?P<path>.*)$', serve,{'document_root': MEDIA_ROOT}),
      
]#+ static(STATIC_URL, document_root=STATIC_ROOT)
if SERVER_ON_HEROKU:
    from django.conf.urls.static import static
    urlpatterns=urlpatterns+static(STATIC_URL, document_root=STATIC_ROOT)

market/views.py
import pusher
import json
from .forms import *
from django.http import HttpResponse,JsonResponse,Http404
from django.shortcuts import render,redirect,reverse
from django.views import View
from app.excel import ReportWorkBook,ReportSheet
from app.settings import *
from app.views import getContext as app_getContext
from .repo import *
from .serializers import *
from app.serializers import CommentSerializer
from app.forms import UploadProfileImageForm,EditProfileForm,ChangeProfileForm
import datetime
if PUSHER_IS_ENABLE:
    from leopusher.models import PusherChannelNameEnum

TEMPLATE_ROOT='market/'
def getContext(request):
    
    user=request.user
    context=app_getContext(request)
    # context['current_profile']=ProfileRepo(user=user).get_by_user(user=user)
    # context['current_shipper']=ShipperRepo(user=user).get_by_user(user=user)
    # context['current_supplier']=SupplierRepo(user=user).get_by_user(user=user)
    # context['current_customer']=CustomerRepo(user=user).get_by_user(user=user)
    # context['current_employee']=EmployeeRepo(user=user).get_by_user(user=user)

    
    active_shipper=ShipperRepo(user=user).me
    active_supplier=SupplierRepo(user=user).me
    active_customer=CustomerRepo(user=user).me
    active_employee=EmployeeRepo(user=user).me
    
 

    context['master_categories']=CategoryRepo(user=user).list_master()
    context['active_shipper']=active_shipper
    context['active_supplier']=active_supplier
    context['active_customer']=active_customer
    context['active_employee']=active_employee





    if active_customer is not None:
        # my_channels=active_customer.channels.all()
        # my_channels_s=MyChannelSerializer(my_channels,many=True).data
        # context['my_channels_s']=json.dumps(my_channels_s)
        cart=CartRepo(user=user).get_by_customer(customer_id=active_customer.pk)
        context['cart']=cart 
        my_list=active_customer.favorites.all()
        context['my_list']=my_list       
    elif active_supplier is not None:
        # my_channels=active_supplier.channels.all()
        # my_channels_s=MyChannelSerializer(my_channels,many=True).data
        # context['my_channels_s']=json.dumps(my_channels_s)
        pass
    elif active_shipper is not None:
        # my_channels=active_shipper.channels.all()
        # my_channels_s=MyChannelSerializer(my_channels,many=True).data
        # context['my_channels_s']=json.dumps(my_channels_s)
        pass
    elif active_employee is not None:
        # my_channels=active_employee.channels.all()
        # my_channels_s=MyChannelSerializer(my_channels,many=True).data
        # context['my_channels_s']=json.dumps(my_channels_s)
        pass
    else:
        pass
    my_channels_s=[]
    context['my_channels_s']=json.dumps(my_channels_s)
    
    context['search_form']=SearchForm()
    parent_categories=CategoryRepo(user=user).list_master()
    context['parent_categories']=parent_categories
    return context


class ManagerView(View):
    def manager(self,request):
        context=getContext(request=request)
        context['send_pusher_beam_form']=pusher_forms.SendPusherBeamForm()
        context['send_pusher_channel_form']=pusher_forms.SendPusherChannelForm()
        context['channel_names']=PusherChannelNameEnum.values
        return render(request,TEMPLATE_ROOT+'manager.html',context)
  

class ShopView(View):
    def list_vue(self,request,*args,**kwargs):
        if 'parent_id' in kwargs:
            parent_id= kwargs.get("parent_id")
        else:
            parent_id=0
        context=getContext(request=request)
        user=request.user
        category_repo=CategoryRepo(user=user)

        
        categories=category_repo.list(parent_id=parent_id)
        if len(categories)>0:
            categories_s=CategorySerializer(categories,many=True).data
            context['categories']=json.dumps(categories_s)
        else:
            context['categories']='[]'

        products=ProductRepo(user=user).list(category_id=parent_id)
        if len(products)>0:
            products_s=ProductSerializer(products,many=True).data
            context['products']=json.dumps(products_s)
        else:
            context['products']='[]'
        parent=category_repo.get(category_id=parent_id)
        if parent is not None:
            parent_s=CategorySerializer(parent).data
            context['parent']=json.dumps(parent_s)
        else:
            context['parent']='{}'

        can_add_category=EmployeeRepo(user=user).me is not None
        can_add_product=EmployeeRepo(user=user).me is not None or SupplierRepo(user=user).me is not None
        can_edit_category=EmployeeRepo(user=user).me is not None
        can_edit_product=EmployeeRepo(user=user).me is not None 
        context['can_add_category']='1' if can_add_category else '0'
        context['can_add_product']='1' if can_add_product else '0'
        context['can_edit_category']='1' if can_edit_category else '0'
        context['can_edit_product']='1' if can_edit_product else '0'
        if can_add_category:
            add_category_form=AddCategoryForm()
            context['add_category_form']=add_category_form
        if can_add_product and not parent_id==0:
            add_product_form=AddProductForm()
            context['add_product_form']=add_product_form
        return render(request=request,template_name=TEMPLATE_ROOT+'list_vue.html',context=context)
    
    
    def list(self,request,*args,**kwargs):
        user=request.user
        if 'parent_id' in kwargs:
            parent_id= kwargs.get("parent_id")
        else:
            parent_id=0
        context=getContext(request=request)
        category_repo=CategoryRepo(user=user)
        product_repo=ProductRepo(user=user)
        categories=category_repo.list(parent_id=parent_id)
        if parent_id==0:            
            products=product_repo.list_for_home()
        else:            
            products=product_repo.list(category_id=parent_id)

        # categories.top_products_length=len(categories.top_products())
        # categories.top_products()=categories.top_products()[:5]
        # for category in categories:
        #     # products=product_repo.top_products(category.id)
        #     # category.top_products=products[:5]
        #     products=
        #     category.count=len(products)
        context['categories']=categories
        # products=product_repo.list_all()
        context['products']=products
        brands=BrandRepo(user=user).list()
        context['brands']=brands
        parent=category_repo.get(category_id=parent_id)
        # print(len(parent.sub_products()))
        # print(parent.sub_products())
        context['parent']=parent
        if parent is not None : context['breadcrumb']=parent.get_breadcrumb()

        can_add_category=(len(products)==0) and (user.has_perm('market.add_category'))
        can_add_product=(len(categories)==0) and (user.has_perm('market.add_product'))
        can_edit_category=SupplierRepo(user=user).me is not None
        can_edit_product=SupplierRepo(user=user).me is not None 

        context['can_add_category']=can_add_category
        context['can_add_product']=can_add_product
        context['can_edit_category']=can_edit_category
        context['can_edit_product']=can_edit_product
        if can_add_category:
            add_category_form=AddCategoryForm()
            context['add_category_form']=add_category_form
        if can_add_product and not parent_id==0:
            add_product_form=AddProductForm()
            context['add_product_form']=add_product_form
            unit_names=ProductUnitRepo(user=user).list()
            context['unit_names']=unit_names
        # return render(request=request,template_name=TEMPLATE_ROOT+'list.html',context=context)
    
        return render(request=request,template_name='one-tech/shop.html',context=context)
    def my_list(self,request,*args,**kwargs):
        user=request.user
        if 'parent_id' in kwargs:
            parent_id= kwargs.get("parent_id")
        else:
            parent_id=0
        context=getContext(request=request)
        category_repo=CategoryRepo(user=user)
        product_repo=ProductRepo(user=user)
        categories=category_repo.list(parent_id=parent_id)
        if parent_id==0:            
            products=product_repo.my_list()
        else:            
            products=product_repo.my_list()

        # categories.top_products_length=len(categories.top_products())
        # categories.top_products()=categories.top_products()[:5]
        # for category in categories:
        #     # products=product_repo.top_products(category.id)
        #     # category.top_products=products[:5]
        #     products=
        #     category.count=len(products)
        context['categories']=categories
        # products=product_repo.list_all()
        context['products']=products
        brands=BrandRepo(user=user).list()
        context['brands']=brands
        parent=category_repo.get(category_id=parent_id)
        # print(len(parent.sub_products()))
        # print(parent.sub_products())
        context['parent']=parent
        if parent is not None : context['breadcrumb']=parent.get_breadcrumb()

        can_add_category=(len(products)==0) and (user.has_perm('market.add_category'))
        can_add_product=(len(categories)==0) and (user.has_perm('market.add_product'))
        can_edit_category=SupplierRepo(user=user).me is not None
        can_edit_product=SupplierRepo(user=user).me is not None 

        context['can_add_category']=can_add_category
        context['can_add_product']=can_add_product
        context['can_edit_category']=can_edit_category
        context['can_edit_product']=can_edit_product
        if can_add_category:
            add_category_form=AddCategoryForm()
            context['add_category_form']=add_category_form
        if can_add_product and not parent_id==0:
            add_product_form=AddProductForm()

templates/market/partials/definition.html
{% load to_persian_date %}
{% load static %}
<div class="card card-stats" >
    <div class="card-header card-header-warning card-header-icon">

      <p class="card-category" style="font-size: 0.75em !important;">
        &nbsp;
      </p> {% verbatim %}
      <p v-html="definition.with_links" class="text-muted my-0"  style="font-size: 1em !important;">
       

      
        

      </p>{% endverbatim %}

    </div>
    <div class="card-footer">
      <div class="btn-group" role="group" aria-label="Basic example">
        <button type="button" class="btn btn-success btn-sm">
          <i class="material-icons">thumb_up</i>
        </button>
        <button class="btn btn-secondary">
          12
        </button>
        <button type="button" class="btn btn-danger btn-sm">
          <i class="material-icons">thumb_down</i>
        </button>
      </div>
      <div class="stats">



        <p class="card-category">



          <a :href="definition.profile.get_absolute_url">


            <img class="" height="24px" width="24px" style="border-radius: 50px;" :src="definition.profile.get_image"
              alt="">


          </a>



          <span style="font-size: 0.75em !important;">
            {% verbatim %}
            {{definition.get_date_added }}
            {% endverbatim %}

          </span>



        </p>
      </div>
    </div>
  </div>

templates/market/partials/product_comment.html
{% load static %}
{% verbatim %}
<div class="media mb-2 pb-2 border-bottom new-comment-style">
    <img class="mr-3 rounded-circle" width="48px" :src="comment.image" alt="Generic placeholder image">
    <div class="media-body">
      <h5 class="mt-0 mb-0">{{comment.name}} <span
          class="mx-2 text-secondary"><small><small>{{comment.persian_time_added}}</small></small></span>
        
          
         
          <!-- <button v-if="comment.profile_id==current_profile_id && confirm_delete_comment"
          @click="CancelDeleteComment" class="btn btn-sm btn-secondary">بازگشت</button> -->

          <button v-if="comment.profile_id==current_profile_id && confirm_delete_comment"
          @click="ConfirmDeleteComment(comment.id)" 
          class="btn btn-sm btn-danger">مطمئنم ، حذف کن</button>
         
          <button  v-if="comment.profile_id==current_profile_id && confirm_delete_comment"
          @click="CancelDeleteComment" type="button" class="close" aria-label="Close">
            <span aria-hidden="true" class="text-secondary">&times;</span>
          </button>


           <button  v-if="comment.profile_id==current_profile_id && !confirm_delete_comment" @click="ShowConfirmDeleteComment" type="button" class="close" aria-label="Close">
            <span aria-hidden="true" class="text-danger">&times;</span>
          </button>
      </h5>
      <small>
        {{comment.comment}}
      </small>
    </div>
  </div>
{% endverbatim %}

templates/market/partials/shop.html
<div>
    <form @submit.prevent="addToCart" action="{% url 'market:add_to_cart' %}" method="POST">

        <button type="submit" class="btn btn-block btn-danger">
            <div class="media">
     <div v-if="waiting" class="spinner-border text-primary" role="status">
                        <span class="sr-only">Loading...</span>
                      </div>
                <div v-if="!waiting"> 
               

                    <i class="material-icons my-auto leo-basket">settings</i></div>


                <div class="media-body ml-3">
                    <h5 class="mt-0">
                        <small>
                            {% verbatim %}

                            هر
                            {{shop.unit_name}}
                            {{to_price(shop.price)}}

                            {% endverbatim %}
                        </small>
                    </h5>
                    <p class="mb-0">

                        {% verbatim %}


                        <small>از
                            {{shop.supplier.name}} بخرید
                        </small>

                        {% endverbatim %}

                    </p>
                </div>
            </div>

        </button>
        {% csrf_token %}
        <input type="hidden" name="product_id" value="{{product.id}}">
        <input type="hidden" name="shop_id" value="shop.id">

    </form>
</div>

templates/market/partials/word.html
{% load to_persian_date %}
<div class="card card-stats">
    <div class="card-header card-header-warning card-header-icon">
     
      
      <p class="card-category" style="font-size: 0.75em !important;">
   &nbsp;
      </p><a href="{{word.get_absolute_url}}">
      <h3 class="card-title text-primary">    {{word.name}}
      
      </h3></a>
       <p class="text-warning my-0" style="font-size: 1em !important;">
        <!-- <span class="text-muted">
تلفظ &nbsp;: &nbsp;
        </span> -->
        {{word.pronounciation}}   
      </p>


      
        {% if word.top_definition.definition %}
            {{word.top_definition.with_links | safe }}   
     
        {% else %}
          تعریفی وجود ندارد
        {% endif %}
        
        

    </div>
    <div class="card-footer">
      <div class="btn-group" role="group" aria-label="Basic example">
       <form action="{% url 'data:add_like' %}" method="POST">
         {% csrf_token %}
         <input type="hidden" name="word_id" value="{{word.id}}">
         <button type="submit" class="btn btn-success btn-sm">
          <i class="material-icons">thumb_up</i>
        </button>
       </form> 
        <button class="btn btn-secondary">
          {{word.get_likes }}
        </button>
        <form action="{% url 'data:add_dislike' %}" method="POST">
          {% csrf_token %}
          <input type="hidden" name="word_id" value="{{word.id}}">
          <button type="submit" class="btn btn-danger btn-sm">
           <i class="material-icons">thumb_down</i>
         </button>
        </form> 
     
       
      </div>
      <div class="stats">
   
     
   
        <p class="card-category" >  
   

     
          <a href="{{word.profile.get_absolute_url}}">

            <img class="" height="24px" width="24px" style="border-radius: 50px;" src="{{word.profile.get_image}}"
            alt="">
          </a>


    
          <br>
 <span style="font-size: 0.75em !important;">{{word.date_added | to_persian_date}}  
          </span>    
       


        </p>
      </div>
    </div>
  </div>