app/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
app_name="app"
urlpatterns = [
    path('',views.BasicView().home,name='home'),
    path('api/',include('app.api')),
    path('my_profile/',views.ProfileView().profile,name='my_profile'),
    path('profile/<int:profile_id>/',views.ProfileView().profile,name='profile'),
    path('transactions/<int:profile_id>/',views.TransactionView().transactions,name='transactions'),    
    path('about/',views.BasicView().about,name='about'),
    path('terms/',views.BasicView().terms,name='terms'),
    path('add_tag/',views.PageView().add_tag,name='add_tag'),
    path('faq/',views.BasicView().faq,name='faq'),
    path('tag/<int:tag_id>/',views.PageView().tag,name='tag'),
    path('blogs/',views.PageView().blogs,name='blogs'),
    path('page/<int:page_id>/',views.PageView().page,name='page'),
    path('add_blog/',views.PageView().add_blog,name='add_blog'),
    path('blog/<int:blog_id>/',views.PageView().blog,name='blog'),
    path('ourworks/',views.PageView().ourworks,name='ourworks'),
    path('ourwork/<int:ourwork_id>/',views.PageView().ourwork,name='ourwork'),
    path('ourservice/<int:ourservice_id>/',views.PageView().ourservice,name='ourservice'),
    path('ourteam/<int:ourteam_id>/',views.BasicView().ourteam,name='ourteam'),
    path('resume/<int:ourteam_id>/',views.BasicView().resume,name='resume'),
    path('change_profile_image/',views.ProfileView().change_profile_image,name='change_profile_image'),
    path('edit_profile/',views.ProfileView().edit_profile,name='edit_profile'),
    path('change_profile/',views.ProfileView().change_profile,name='change_profile'),
    path('search/',views.BasicView().search,name='search'),
    path('manager/',views.ManagerView().manager,name='manager'),
    path('contact/',views.ContactView.as_view(),name='contact'),
    path('notifications/',views.BasicView().notifications,name='notifications'),
    path('notification/<int:notification_id>/',views.BasicView().notifications,name='notification'),
    path('download/<int:document_id>/',views.BasicView().download,name='download'),
    path('technology/<int:technology_id>/',views.PageView().technology,name='technology'),
    
]

market/urls.py
from django.urls import path,include
from .views import *
app_name='market'
urlpatterns=[  
    
    path('api/', include('market.api')),
    path('',ShopView().list,name='home'),
    path('my_list/',IndexView().my_list,name='my_list'),
    path('suppliers/',SupplierView().list,name='suppliers'),
    path('submit_cart/',CartView().submit_cart,name='submit_cart'),
    path('orders/<int:customer_id>/',OrderView().orders,name='orders'),
    path('orders_/<int:supplier_id>/',OrderView().orders,name='orders_supplier'),
    path('orders_/<int:supplier_id>/<start_date>/<end_date>/',OrderView().orders,name='orders_supplier_by_date'),
    path('orders__/<int:shipper_id>/',OrderView().orders,name='orders_shipper'),
    path('cart/<int:customer_id>/',CartView.as_view(),name='cart'),
    path('order/<int:order_id>/',OrderView().order,name='order'),
    path('do_pack_order/',OrderView().do_pack_order,name='do_pack_order'),
    path('do_deliver_order/',OrderView().do_deliver_order,name='do_deliver_order'),
    path('do_ship_order/',OrderView().do_ship_order,name='do_ship_order'),
    path('add_category/',ShopView().add_category,name='add_category'), 
    path('add_product/',ShopView().add_product,name='add_product'), 
    path('add_shop/',ShopView().add_shop,name='add_shop'), 
    path('add_product_comment/',ProductView().add_product_comment,name='add_product_comment'), 
    path('remove_shop/',ShopView().remove_shop,name='remove_shop'), 
    path('add_to_cart/',ProductView().add_to_cart,name='add_to_cart'),    
    path('remove_from_cart/',CartView().remove_from_cart,name='remove_from_cart'), 
    path('tables/',TableView().list,name='tables'),    
    path('xlsx/',ProductView().get_list_xlsx,name='xlsx'),
    path('brand/<int:brand_id>/',ShopView().brand,name='brand'),
    path('products/<int:category_id>/',ProductView().list,name='products'),
    path('product/<int:product_id>/',ProductView().product,name='product'),
    path('list/<int:parent_id>/',IndexView.as_view(),name='list'),
    path('list_vue/<int:parent_id>/',ShopView().list_vue,name='list_vue'),
    path('supplier/<int:supplier_id>/',SupplierView().supplier,name='supplier'),
    path('ware_house/<int:ware_house_id>/',WareHouseViews().ware_house,name='ware_house'),
    path('download/<int:supplier_id>/',DownloadView.as_view(),name='download'),
    path('download/order/<int:order_id>/',DownloadView().get_order,name='download_order'),
    # path('w/d/<name>/',views.WordView().word_name,name='word_name'),
    # path('new_definition/',views.WordView().new_definition,name='new_definition'),
    # path('new_word/',views.WordView().new_word,name='new_word'),
    path('add_like/',ProductView().add_like,name='add_like'),
    # path('add_dislike/',views.WordView().add_dislike,name='add_dislike'),
    path('search/',IndexView().search,name='search'),

    path('manager/',ManagerView().manager,name='manager'),
    


    
]

phoenix/urls.py
from django.contrib import admin
from django.urls import path,include


# from django.conf import settings
from .settings import MEDIA_URL,MEDIA_ROOT,STATIC_URL,STATIC_ROOT,DEBUG
from django.views.static import serve 
from django.conf.urls import url
from .settings import SERVER_ON_HEROKU
from app.feeder import LatestEntriesFeed,SiteMapFeeder

urlpatterns = [
    path('', include('app.urls')),
    path('phoenix_app/', include('app.urls')),
    
    path('pusher/', include('leopusher.urls')),
    path('tutorial/', include('tutorial.urls')),
    path('projectmanager/', include('projectmanager.urls')),
    path('transport/', include('transport.urls')),
    path('phoenix_api/', include('phoenix_api.urls')),
    path('accounting/', include('accounting.urls')),
    path('fa/', include('app.urls')),
    path('en/', include('engapp.urls')),
    path('automation/', include('automation.urls')),
    path('market/', include('market.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('authentication.urls')),
    path('', include('authentication.urls')),    
    path('rss/', LatestEntriesFeed(),name='feeder'),
    path('sitemap/', SiteMapFeeder(),name='sitemap'),
    url(r'^static/(?P<path>.*)$', serve,{'document_root': STATIC_ROOT}),
    url(r'^media/(?P<path>.*)$', serve,{'document_root': MEDIA_ROOT}),
      
]#+ static(STATIC_URL, document_root=STATIC_ROOT)
if SERVER_ON_HEROKU:
    from django.conf.urls.static import static
    urlpatterns=urlpatterns+static(STATIC_URL, document_root=STATIC_ROOT)

templates/one-tech/cart.html
{% extends "one-tech/layout.html" %}
{% load static %}
{% load to_price %}
{% block header %}
<link rel="stylesheet" type="text/css" href="{% static 'one-tech/styles/cart_styles.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'one-tech/styles/cart_responsive.css' %}">

{% endblock  %}



{% block contents %}

<!-- Cart -->

<div class="cart_section">
	<div class="container">
		<div class="row">
			<div class="col-lg-10 offset-lg-1">
				<div class="cart_container">
					<div class="cart_title leo-farsi text-right">سبد خرید</div>

					{% if cart.orders %}
					<div class="cart_items">
						<ul class="cart_list">
							{% for cart_line in cart.lines %}
							<li class="cart_item clearfix leo-rtl text-right">
								<div class="media">
									<div>
										<div class="cart_item_image"><img src="{{cart_line.shop.product.get_image}}"
												alt="">
										</div>
									</div>
									<div class="media-body">
										<div class="cart_item_title">
											<a class=" leo-farsi" href="{{cart_line.shop.product.get_absolute_url}}">
												{{cart_line.shop.product.name}}
											</a>

											<a class=" mx-2 leo-farsi text-secondary"
												href="{{cart_line.shop.supplier.get_absolute_url}}">
												{{cart_line.shop.supplier.name}}
											</a>
										</div>
										<div class="cart_item_text  leo-farsi">

											{{cart_line.quantity}} {{cart_line.shop.unit_name}}


											<span class="mx-3 text-secondary" style="width: fit-content;">
												{{cart_line.shop.price | to_price}}

											</span>


											{{cart_line.total | to_price}}


										</div>
									</div>
									{% if remove_from_cart_form %}

									<div class="media-footer">

										<span v-if='!accept_delete' style="cursor: pointer;" @click="toggle_accept_delete"
										 type="submit" class="text-danger">
											<i class="material-icons">delete</i>
										</span>

										<form action="{% url 'market:remove_from_cart' %}" method="POST">
											{% csrf_token %}
											<input type="hidden" name="shop_id" value="{{cart_line.shop.id}}">
											<button  style="cursor: pointer;" type="submit" v-if='accept_delete' class="btn btn-link btn-danger">
												<i class="material-icons">delete</i>
											</button>
											<span   style="cursor: pointer;" @click="toggle_accept_delete" v-if='accept_delete'
										 type="submit" class="text-dark">
											<i class="material-icons">clear</i>
										</span>
										</form>
									</div>

									{% endif %}

								</div>
							</li>{% endfor %}
							
						</ul>
					</div>

					<!-- Order Total -->
					<div class="order_total">
						<div class="order_total_content text-md-right leo-rtl text-right leo-farsi">


							<div class="order_total_title">جمع اقلام : </div>
							<div class="order_total_amount">

								{{cart.total | to_price}}
							</div>

						</div>
					</div>

					<div class="cart_buttons">

						{% for order in cart.orders %}
						<form action="{% url 'market:submit_cart' %}" method="post" class="my-2">
							{% csrf_token %}
							<input type="hidden" name="customer_id" value="{{cart.customer.id}}">
							<input type="hidden" name="address" value="address address">
							<input type="hidden" name="description" value=" ">
							<input type="hidden" name="supplier_id" value="{{order.supplier.id }}">
							<button type="submit" class="button cart_button_checkout">
								تایید پیش فاکتور {{order.supplier.name}}
							</button>
						</form>


						{% endfor %}
						<!-- <button type="button" class="button cart_button_clear">تایید سبذ خرید</button>
						<button type="button" class="button cart_button_checkout">Add to Cart</button> -->
					</div>
					{% else %}
					<!-- Order Total -->
					<div class="order_total">
						<div class="order_total_content text-md-right leo-rtl text-right leo-farsi">


							<div class="order_total_title"></div>
							<div class="order_total_amount">
								سبد خرید شما خالی می باشد
							</div>

						</div>
					</div>
					{% endif %}

				</div>
			</div>
		</div>
	</div>
</div>


{% endblock  %}



{% block scripts %}
<script src="{% static 'vendor/js/vue.js' %}"></script>
<script>
	let cart_app = new Vue(
		{
			el: ".cart_section",
			data: {
				accept_delete: false,
			},
			methods: {
				toggle_accept_delete() {
					if (this.accept_delete) {
						this.accept_delete = false
						return this.accept_delete
					}
					if (!this.accept_delete) {
						this.accept_delete = true
						return this.accept_delete
					}

				},
			}
		}
	)
	
</script>
{% endblock  %}

templates/one-tech/empty.html
{% extends "one-tech/layout.html" %}
{% load static %}
{% block header %}
  
{% endblock  %}



{% block contents %}
  
{% endblock  %}



{% block scripts %}
  
{% endblock  %}

templates/one-tech/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>


	<!-- MetaData -->

    <meta name="description"
        content="{% for meta_data in app.meta_data_items.all %}{{meta_data.content}} , {% endfor %}" />



    <meta name="description"
        content="Author:Hossein Moghimi ,{% for meta_data in app.meta_data_items %}{{meta_data.content}} , {% endfor %}" />


    <meta name="robots"
        content="Author:Hossein Moghimi ,{% for meta_data in app.meta_data_items %}{{meta_data.content}} , {% endfor %}" />



		
	<title> {{app.pretitle.value}} " {{app.title.value}} "</title>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="description" content="OneTech shop project">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" type="text/css" href="{% static 'one-tech/styles/bootstrap4/bootstrap.min.css' %}">
	<link href="{% static 'one-tech/plugins/fontawesome-free-5.0.1/css/fontawesome-all.css' %}" rel="stylesheet"
		type="text/css">
	<link rel="stylesheet" type="text/css" href="{% static 'one-tech/plugins/OwlCarousel2-2.2.1/owl.carousel.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'one-tech/plugins/OwlCarousel2-2.2.1/owl.theme.default.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'one-tech/plugins/OwlCarousel2-2.2.1/animate.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'one-tech/plugins/jquery-ui-1.12.1.custom/jquery-ui.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'one-tech/leo/css/leo.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'leo/css/font-awesome.min.css' %}">




	<!--     Fonts and icons     -->
	<link rel="stylesheet" type="text/css" href="{% static 'dashboard/icons/css.css' %}" />
	<link rel="stylesheet" href="{% static 'dashboard/icons/font-awesome.min.css' %} ">


	<link rel="stylesheet" href="{% static 'dashboard/fonts/fontawesome-webfont.woff2' %} ">
	<!-- Markazi Text font include just for persian demo purpose, don't include it in your project -->
	<style>
		.header_search_button2 {
			/* position: absolute; */
			top: 0;
			left: 0;
			width: 50px;
			height: 100%;
			background: #0e8ce4;
			border: none;
			outline: none;
			cursor: pointer;
			border-top-left-radius: 5px;
			border-bottom-left-radius: 5px;
		}
		.page_menu_item {
			text-align: right;
		}
		a{
			text-align: right;
		}
	</style>
	{% block header %}

	{% endblock %}
</head>

<body>

	<div class="super_container">
{% include 'one-tech/includes/header.html' %}

		{% block contents %}

		{% endblock  %}

	{% if brands %}
	  
	{% include "one-tech/includes/brands.html" %}
	{% endif %}
		{% include "one-tech/includes/newsletter.html" %}
		{% include "one-tech/includes/footer.html" %}
	</div>

	<script src="{% static 'one-tech/js/jquery-3.3.1.min.js' %}"></script>
	<script src="{% static 'one-tech/styles/bootstrap4/popper.js' %}"></script>
	<script src="{% static 'one-tech/styles/bootstrap4/bootstrap.min.js' %}"></script>
	<script src="{% static 'one-tech/plugins/greensock/TweenMax.min.js' %}"></script>
	<script src="{% static 'one-tech/plugins/greensock/TimelineMax.min.js' %}"></script>
	<script src="{% static 'one-tech/plugins/scrollmagic/ScrollMagic.min.js' %}"></script>
	<script src="{% static 'one-tech/plugins/greensock/animation.gsap.min.js' %}"></script>
	<script src="{% static 'one-tech/plugins/greensock/ScrollToPlugin.min.js' %}"></script>
	<script src="{% static 'one-tech/plugins/OwlCarousel2-2.2.1/owl.carousel.js' %}"></script>
	<script src="{% static 'one-tech/plugins/easing/easing.js' %}"></script>
	<!--  Notifications Plugin    -->
	<script src="{% static 'dashboard/js/plugins/bootstrap-notify.js' %}"></script>
	<!-- Control Center for Material Dashboard: parallax effects, scripts for the example pages etc -->

	<!-- <script src="{% static 'vendor/js/material-dashboard.js' %}"></script> -->

	{% block scripts %}

	{% endblock %}
</body>

</html>

templates/one-tech/search.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <p>search:</p>
    {% for product in products %}
      <div>
          <a href="{{product.get_absolute_url}}">
          {{product.name}}</a>
      </div>
    {% endfor %}
</body>
</html>

templates/one-tech/shop.html
{% extends "one-tech/layout.html" %}
{% load to_price %}
{% load static %}
{% load to_price_pure %}
{% block header %}

<link rel="stylesheet" type="text/css" href="{% static 'one-tech/styles/shop_styles.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'one-tech/styles/shop_responsive.css' %}">

{% endblock %}
{% block contents %}

<!-- Home -->

<div class="home">
	<div class="home_background parallax-window" data-parallax="scroll"
		data-image-src="{% static 'one-tech/images/shop_background.jpg' %}"></div>
	<div class="home_overlay"></div>
	<div class="home_content d-flex flex-column align-items-center justify-content-center">

		{% if parent %}
		{{breadcrumb | safe}}
		<h2 class="home_title">
			{{parent.name}}</h2>
		{% else %}
		<h2 class="home_title"> فروشگاه
		</h2> {% endif %}

	</div>
</div>


<!-- Shop -->

<div class="shop" id="shop-app">
	<div class="container">
		<div class="row leo-rtl">
			<div class="col-lg-3">

				<!-- Shop Sidebar -->
				<div class="shop_sidebar">
					{% if categories %}

					<div class="sidebar_section">
						<div class="sidebar_title text-right leo-farsi"> دسته بندی</div>
						<ul class="sidebar_categories">
							{% for category in categories %}
							<li style="text-align: right;"><a class="leo-farsi text-primary"
									href="{{category.get_absolute_url}}">{{category.name}}</a></li>

							{% endfor %}

						</ul>
					</div>
					{% endif %}
					<div class=" d-none sidebar_section filter_by_section">
						<div class="sidebar_title  leo-farsi text-right">
							<p>فیلتر کن</p>
						</div>
						<div class="sidebar_subtitle  leo-farsi text-right ">قیمت</div>
						<div class="filter_price">
							<div id="slider-range" class="slider_range"></div>
							<p>محدوده: </p>
							<p><input type="text" id="amount" class="amount" readonly
									style="border:0; font-weight:bold;"></p>
						</div>
					</div>

					<div class="sidebar_section d-none ">
						<div class="sidebar_subtitle color_subtitle  leo-farsi text-right">رنگ</div>
						<ul class="colors_list text-right">
							<li class="color text-right"><a href="#" style="background: #b19c83;"></a></li>
							<li class="color text-right"><a href="#" style="background: #000000;"></a></li>
							<li class="color text-right"><a href="#" style="background: #999999;"></a></li>
							<li class="color text-right"><a href="#" style="background: #0e8ce4;"></a></li>
							<li class="color text-right"><a href="#" style="background: #df3b3b;"></a></li>
							<li class="color text-right"><a href="#"
									style="background: #ffffff; border: solid 1px #e1e1e1;"></a>
							</li>
						</ul>
					</div>
					<div class="sidebar_section mt-4 ">
						<div class="sidebar_title text-right leo-farsi"> برند ها </div>

						<ul class="brands_list">
							{% for brand in brands %}
							<li style="text-align: right;"><a class="leo-farsi"
									href="{{brand.get_absolute_url}}">{{brand.name}}</a></li>

							{% endfor %}
						</ul>
					</div>
				</div>

			</div>

			<div class="col-lg-9">

				<!-- Shop Content -->

				<div class="shop_content">
					<div class="shop_bar clearfix leo-rtl">
						<div class="shop_product_count">
							<span class=" leo-farsi">
								تعداد : {{products|length}}
							</span>
						</div>
						<div class="shop_sorting leo-farsi">
							<span class="leo-farsi">ترتیب بر اساس : </span>
							<ul>
								<li>
									<span class="sorting_text">محبوب ترین<i class="fas mx-1 fa-chevron-down"></span></i>
									<ul>
										<li class="shop_sorting_button" @click="log_test('ارزان ترین')"
											data-isotope-option='{ "sortBy": "original-order" }'>ارزان ترین</li>
										<li class="shop_sorting_button" @click="log_test('نام')"
											data-isotope-option='{ "sortBy": "name" }'>نام
										</li>
										<li class="shop_sorting_button" @click="log_test('قیمت')"
											data-isotope-option='{ "sortBy": "price" }'>
											قیمت</li>
									</ul>
								</li>
							</ul>

						</div>
					</div>

					<div class="mt-2">
						<div class="product_grid_border"></div>
						<div class="row">

							{% for product in products %}
							<!-- Product Item -->
							<div
								class="col-lg-3 col-md-4 col-sm-6 col-6 {% if product_related.is_new %}is_new{% endif %} {% if product_related.discount %}discount{% endif %} product_item is_new">
								<div class="product_border"></div>
								<div
									class="product_image  d-flex flex-column align-items-center justify-content-center">
									<a href="{{product.get_absolute_url}}"><img src="{{product.get_thumbnail}}"
											alt=""></a>
								</div>
								<div class="product_content">
									<div class="product_price">&nbsp;</div>
									<div class="product_name">
										<div>
											<a href="{{product.get_absolute_url}}" class="leo-farsi text-center"
												tabindex="0">
												
												{{product.name}}
												{% if product.model_name %}
												<br>
												<span class="text-secondary">{{product.model_name}}</span>
												{% endif %}

												{% if product.origin_price %}
												<br>
												<span class="">
													{{product.origin_price|to_price}}</span>
												{% endif %}
										</a>

										</div>
									</div>
								</div>{% if perms.market.change_product %}
								<div class="product_fav1">

									<a href="{{product.get_edit_url}}" class="leo-farsi"><i
											class="material-icons">settings</i> ویرایش</a>

								</div>{% endif %}
								<ul class="product_marks">
									{% if product.is_new %}
									<li class="product_mark product_new leo-farsi">جدید</li>
									{% elif product.discount %}
									<li class="product_mark product_discount1 leo-farsi"
										style="background-color:#df3b3b !important;display: inline-block!important;">
										{{product.discount}}%</li>

									{% endif %}
								</ul>
							</div>
							{% endfor %}

							{% if add_product_form %}
							<div class="col-lg-4 mx-5">
								<div class="card p-3">
									<h3 class="text-center my-3">افزودن کالای جدید</h3>
									<form class="leo-rtl text-right" action="{% url 'market:add_product' %}"
										method="POST">
										{% csrf_token %}
										<input type="hidden" value="{{parent.id}}" name="category_id">

										<select style="width: fit-content !important;" name="unit_name" id=""
											class="form-control">
											{% for unit_name in unit_names %}
											<option value="{{unit_name}}">{{unit_name}}</option>
											{% endfor %}
										</select>
										<input type="text" name="name" class="form-control" placeholder="نام کالا"
											required id="">
										<input type="submit" class="btn btn-success" value="تایید">
									</form>
								</div>
							</div>
							{% endif %}
						</div>

					</div>


					<!-- Shop Page Navigation -->

					<div class="shop_page_nav d-flex flex-row justify-content-center">
						<div class="page_prev d-flex flex-column align-items-center justify-content-center"><i
								class="fas fa-chevron-right"></i></div>
						<ul class="page_nav d-flex flex-row">
							<li><a href="#">1</a></li>
							<li><a href="#">2</a></li>
							<li><a href="#">3</a></li>
							<li><a href="#">...</a></li>
							<li><a href="#">21</a></li>
						</ul>
						<div class="page_next d-flex flex-column align-items-center justify-content-center"><i
								class="fas fa-chevron-left"></i></div>
					</div>

				</div>

			</div>
		</div>
	</div>
</div>

<!-- Recently Viewed -->

<div class="viewed">
	<div class="container">
		<div class="row">
			<div class="col">
				<div class="viewed_title_container">
					<h3 class="viewed_title text-right">محصولات مرتبط</h3>
					<div class="viewed_nav_container" style="left: 5px!important; right:none;">
						<div class="viewed_nav viewed_prev"><i class="fas fa-chevron-left"></i></div>
						<div class="viewed_nav viewed_next"><i class="fas fa-chevron-right"></i></div>
					</div>
				</div>

				<div class="viewed_slider_container">

					<!-- Recently Viewed Slider -->

					<div class="owl-carousel owl-theme viewed_slider">

						{% for product_related in products %}
						<!-- Recently Viewed Item -->
						<div class="owl-item">
							<div
								class="viewed_item {% if product_related.is_new %}is_new{% endif %}{% if product_related.discount %}discount{% endif %} d-flex flex-column align-items-center justify-content-center text-center">
								<div class="viewed_image">
									<a href="{{product_related.get_absolute_url}}">

										<img src="{{product_related.get_image}}" alt="">

									</a>
								</div>
								<div class="viewed_content text-center">
									<!-- <div class="viewed_price">$225<span>$300</span></div> -->
									<div class="viewed_name"><a href="{{product_related.get_absolute_url}}"
											class=" leo-farsi">{{product_related.name}}</a></div>
								</div>
								<ul class="item_marks">
									{% if product_related.is_new %}
									<li class="item_mark item_new leo-farsi">جدید</li>
									{% endif %}
									{% if product_related.discount %}
									<li class="item_mark item_discount">{{product_related.discount}}%</li>
									{% endif %}
								</ul>
							</div>
						</div>


						{% endfor %}


					</div>

				</div>
			</div>
		</div>
	</div>
</div>




{% endblock  %}
{% block scripts %}
<script src="{% static 'one-tech/plugins/Isotope/isotope.pkgd.min.js' %}"></script>
<script src="{% static 'one-tech/plugins/jquery-ui-1.12.1.custom/jquery-ui.js' %}"></script>
<script src="{% static 'one-tech/plugins/parallax-js-master/parallax.min.js' %}"></script>
<script src="{% static 'one-tech/js/shop_custom.js' %}"></script>


<script src="{% static 'vendor/js/vue.js' %}"></script>
<script src="{% static 'leo/js/utility.js' %}"></script>


<script>
	let csrfmiddlewaretoken = ''
	$(document).ready(function () {
		// Javascript method's body can be found in assets/js/demos.js
		csrfmiddlewaretoken = $("input[name='csrfmiddlewaretoken']").val()


		$('.owl-carousel').owlCarousel({
			rtl: true,
			loop: true,
			margin: 10,
			autoplay: true,
			autoplayTimeout: 4000,
			autoplayHoverPause: true,
			responsive: {
				0: {
					items: 1
				},
				600: {
					items: 3
				},
				1000: {
					items: 4
				}
			}
		})




	});

	$(function () {
		$('[data-toggle="popover"]').popover()
	})



	function add_like_post(product_id) {
		url = "{% url 'market:add_like' %}"
		var posting = $.post(url, { product_id: product_id, csrfmiddlewaretoken: csrfmiddlewaretoken });

		posting.done(function (data) {
			// product_app.is_liked = data.is_liked
		})
	}



	let shop_app = new Vue(
		{
			el: "#shop-app",
			data: {

			},
			methods: {
				add_like: function (product_id) {
					add_like_post(product_id)
					console.log(product_id)
				},
				log_test: function (text) {
					console.log(text)
				},
			}
		}
	)
</script>
{% endblock %}